version: '3.9'

services:
  db:
    build: ./db
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 3
  app:
    build: ./app
    ports:
     - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  api:
    build: ./api
    ports:
     - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  
     